apache/seatunnel

src/main/antlr4/PluginDoc.g4
src/main/antlr4/PluginDocExample.docs
src/main/java/org/interestinglab/waterdrop/docutils/PluginDoc.java
src/main/java/org/interestinglab/waterdrop/docutils/PluginDocCommand.java
src/main/java/org/interestinglab/waterdrop/docutils/PluginDocMarkdownRender.java
src/main/java/org/interestinglab/waterdrop/docutils/PluginDocRuntimeException.java

Plugin document自动生成功能：
功能描述：根据plugin开发者定义的*.docs文件，自动生成markdown文件
优点：
* plugin document 定义方式相同，展现格式统一，可程序解析。
示例：执行命令：
```
sbt "run-main org.interestinglab.waterdrop.docutils.PluginDocCommand src/main/antlr4/PluginDocExample.docs"
```
PluginDocExample.docs内容：
```
@waterdropPlugin
@pluginGroup input
@pluginName kafka
@pluginDesc "get message from kafka"
@pluginAuthor garyelephant
@pluginHomepage https://interestinglab.github.io/waterdrop
@pluginVersion 1.2.3
@pluginOption array topics yes "a list of topics to consume"
@pluginOption string consumer.bootstrap.servers yes "kafka broker list"
@pluginOption string consumer.group.id yes "consumer group id"
@pluginOption number consumer.num.consumer.fetchers="2" no
```
---
输出如下markdown内容：
* Author: garyelephant
* Homepage: …

Garyelephant.fea.plugin docs

---

src/main/scala/org/interestinglab/waterdrop/filter/Json.scala
src/main/scala/org/interestinglab/waterdrop/filter/Split.scala

更新了当`target_filter` 为 __root__时的处理逻辑，相比之前的逻辑有以下几点优势
1. 无需重新创建DataFrame，能节省一定性能
2. 无法编写`StructField`，减少处理流程编写的难度
2. 复用`split`方法，代码更加简洁。

Update filter json

---

src/main/scala/org/interestinglab/waterdrop/filter/Json.scala

JSON插件的新尝试
- 支持嵌套结构
- 支持`target_field`为*ROOT*
缺点
- 获取`schema`的时候消耗了性能，需要解析两次JSON

Rickyhuo.enhance.json

---

bin/start-waterdrop.sh
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/CommandLineUtils.scala
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Sql.scala

* enhanced the useage of variable substitution:
```
./bin/start-waterdrop.sh -c ./config/variable-substitution.conf.template -e cluster -m yarn -i city2=shanghai -i dt=20190319
./bin/start-waterdrop.sh -c ./config/variable-substitution.conf.template -e client -m yarn -i city2=shanghai -i dt=20190319
./bin/start-waterdrop.sh -c ./config/variable-substitution.conf.template -e client -m local[2] -i city2=shanghai -i dt=20190319
```
option `-i` is same as  `--variable` in  variable substitution.

Garyelephant.variables substitution

---

build.md
build.sbt
waterdrop-apis/build.sbt
waterdrop-core/build.sbt

* Fixed waterdrop-xxx.zip packaging in windows
* Removed all duplicate dependencies for spark and hadoop in assembly jar, making the size of assembly jar less than 60MB.
* Updated build.md

Removed all duplicate dependencies for spark and hadoop in assembly jar

---

waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/JdbcConnectionPoll.java
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/structuredstreaming/Jdbc.scala

fix structured-streaming jdbc output exception:
```
Caused by: org.apache.spark.SparkException: Task not serializable
at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:403)
at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:393)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
at org.apache.spark.SparkContext.runJob(SparkContext.scala:2056)
at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:64)
... 35 more
Caused by: java.io.NotSerializableException: java.io.PrintWriter
Serialization stack:
- object not serializable (class: java.io.PrintWriter, value: …
```

make jdbc output for structstreaming work

---

waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/Waterdrop.java
waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/CompressionUtils.java

v2 spark json解析插件在cluster模式下无法找到json  schema文件，原因是wd v2没有像v1那样针对cluster上传的plugins文件做过处理，此pr修复了。

fixed v2 spark cluster mode plugins.tar.gz error

---

plugin-spark-phoenix-core/pom.xml
plugin-spark-sink-hbase/pom.xml
plugin-spark-sink-hbase/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.spark.BaseSparkSink
plugin-spark-sink-hbase/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Hbase.scala
plugin-spark-sink-hbase/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/HbaseSaveMode.scala
pom.xml
waterdrop-core/pom.xml

Depends on `hbase-connectors`, we could load(bulk load) data into hbase by spark.
For fixing version conflicts, i changed `org.apache.phoenix.phoenix-spark` dependency version of `plugin-spark-phoenix-core`  to `5.0.0-HBase-2.0 `
PTAL
@garyelephant @RickyHuo

Feature: add spark sink hbase plugin

---

waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/CompressionUtils.java

It's more portable to use slf4j instead of specific logger implementation.

use slf4j Logger instead of log4j Logger

---

waterdrop-common/pom.xml

See document on official site, It's no need to include lombok jar in release package: https://projectlombok.org/setup/maven#adding-lombok-to-your-pom-file

change lombok scope to 'provided'

---

waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/Waterdrop.java

use "java.nio.file.Paths" instead of "org.apache.hadoop.fs.Path" to  extract file name to reduce dependency in module waterdrop-core.

reduce waterdrop-core module's dependency

---

seatunnel-dist/assembly.xml

Binary files are best to add the bin suffix
The package file is modified to tar.gz format

Increase the file type and format of the package generated file

---

plugin-spark-sink-elasticsearch/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Elasticsearch.scala

---
Since Elasticsearch 6.0, the use of multiple types is gradually not recommended, and from Elasticsearch 7.0, the support for multiple types is gradually removed. The default type used in Elasticsearch 7.0 internal index is _doc, so it is recommended to change the default value of type to _doc for a more concise and fast configuration.
The code of the critical link is not modified, only the default value of type is modified.

change es sink plugin index_type default value from log to _doc

---

pom.xml

Delete the developer’s personal information to avoid unnecessary ambiguity.

Delete developer info

---

pom.xml
seatunnel-core/seatunnel-core-sql/pom.xml
seatunnel-core/seatunnel-core-sql/src/main/java/io/github/interestinglab/waterdrop/core/sql/job/Executor.java

Fixed #836 
We need to start a standalone flink cluster first, then we can submit sql job in the past, beacuse the sql job is always run asynchronously by default. We can support set operation statements in sql configuration, like `SET table.dml-sync = true;` statement. After that we can run sql job in foreground.
Yeah, support run job in the foreground is just only one of the reasons for introducing this feature.
The keypoint of this feature is to support set operation.
1. flink home
```
export FLINK_HOME=/work/BigData/install/flink/flink-1.13.3
```
2. application.conf
```
SET table.dml-sync = true;
CREATE TABLE events (
f_type INT,
f_uid INT,
ts AS localtimestamp,
WATERMARK FOR ts AS ts
) WITH (
'connector' = 'datagen',
'rows-per-second'='5',
'fields.f_type.min'='1', …
```

[SeaTunnel #836] [sql] Support set operation statements in sql configuration

---

deploy/docker/flink/README.md

Fixed #846 
When run flink docker demo, met two exceptions
**1. Can not find the config file**
```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: No configuration setting found for key 'env'
at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:593)
at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:438)
at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
at …
```

[SeaTunnel #846] [docker] flink quick start demo run failed

---

waterdrop-apis/src/main/scala/io/github/interestinglab/waterdrop/apis/BaseAction.java
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/ConfigBuilder.scala

Define an action to do whatever you want on execution started or finished,
the sequence will be as follows:
```
program started ..
BaseAction::onExecutionStarted()
for loop for data:
Source --> Transform --> Sink
BaseAction::onExecutionFinished()
program finished ..
```
Attention:
1. For now, this only apply for batch processing, not for streaming or structured streaming processing

[v1] added the abstraction of BaseAction

---

seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/BaseSparkSink.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/BaseSparkSource.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/SparkEnvironment.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/batch/SparkBatchExecution.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/stream/SparkStreamingExecution.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/stream/SparkStreamingSource.scala
seatunnel-apis/seatunnel-api-spark/src/main/scala/org/apache/seatunnel/spark/structuredstream/StructuredStreamingExecution.scala
seatunnel-connectors/plugin-flink-source-fake/src/main/java/org/apache/seatunnel/flink/source/FakeSourceStream.java
seatunnel-connectors/plugin-spark-sink-clickhouse/src/main/scala/org/apache/seatunnel/spark/sink/Clickhouse.scala
seatunnel-connectors/plugin-spark-sink-doris/src/main/scala/org/apache/seatunnel/spark/sink/Doris.scala
seatunnel-connectors/plugin-spark-sink-doris/src/main/scala/org/apache/seatunnel/spark/sink/DorisUtil.scala
seatunnel-connectors/plugin-spark-sink-hbase/src/main/scala/org/apache/seatunnel/spark/sink/Hbase.scala
seatunnel-connectors/plugin-spark-sink-kafka/src/main/scala/org/apache/seatunnel/spark/sink/Kafka.scala
seatunnel-connectors/plugin-spark-source-kudu/src/main/scala/org/apache/seatunnel/spark/source/Kudu.scala
seatunnel-transforms/plugin-spark-transform-json/src/main/scala/org/apache/seatunnel/spark/transform/Json.scala
seatunnel-transforms/plugin-spark-transform-split/src/main/scala/org/apache/seatunnel/spark/transform/Split.scala
seatunnel-transforms/plugin-spark-transform-sql/src/main/scala/org/apache/seatunnel/spark/transform/Sql.scala

[Feature #861][ALL] Remove useless imports

---

waterdrop-config/src/main/java/io/github/interestinglab/waterdrop/config/impl/ConfigParser.java
waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseAction
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/action/Jdbc.scala
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/action/batch/Jdbc.scala
waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/ConfigBuilder.scala

add jdbc action
Users can use this feature to execute some SQL before the data is imported and some SQL after the data is imported.
```
action {
jdbc {
driver = "com.mysql.jdbc.Driver"
url = "jdbc:mysql://localhost:3306/databasename"
user = "xxx"
password = "xxxx"
before {
errorSqlIgnored = true //default false
actions = [
"create table my_tb4 (id varchar(5))"
"create table my_tb5 (id varchar(5))"
]
}
after {
errorSqlIgnored = true //default false
actions = [
"show tables"
]
}
}
}
```

[v1] [feature] add jdbc action

---

README.md

Signed-off-by: Al-assad yulin.ying@outlook.com
The logo image in the current README is pointing to an incorrect link:  
And this is the effect after fixing the link:

[typo] Fix the wrong logo image link in README

---

seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/utils/CompressionUtils.java

This PR fixes the wrong link in Java doc for `CompressionUtils`.

Fix the wrong link in java doc for CompressionUtils

---

seatunnel-examples/seatunnel-flink-examples/pom.xml

Resolve ConfigParser class conflict between Seatunnel and Flink.
Native debugging increases flink's default ConfigParser priority.
The modified：

[Feature][seatunnel-examples] Resolve ConfigParser class conflict between Seatunnel and Flink.

---

config/flink.batch.conf.template

Some params in `flink.batch.conf.template` are deprecated, we need to update them.
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-connectors/seatunnel-connector-flink-file/src/main/java/org/apache/seatunnel/flink/source/FileSource.java
```
2022-01-12 04:39:40,911 ERROR org.apache.seatunnel.Seatunnel  - Plugin[org.apache.seatunnel.flink.source.FileSource] contains invalid config, error: please specify [path] as non-empty 
```

[hotfix] Fix wrong params in flink batch template
