src/main/scala/org/interestinglab/waterdrop/WaterdropMain.scala, src/main/scala/org/interestinglab/waterdrop/input/BaseInput.scala, src/main/scala/org/interestinglab/waterdrop/input/Kafka.scala, src/main/scala/org/interestinglab/waterdrop/output/BaseOutput.scala
*  确定了BaseInput, BaseOutput接口
* 支持多个input, output
=> Garyelephant.fea.baseinput baseoutput

build.sbt, src/main/scala/org/interestinglab/waterdrop/output/Elasticsearch.scala
实现基本写入Elasticsearch的功能， 暂未实现模板渲染
=> Rickyhuo.fea.elasticsearch

src/main/java/org/interestinglab/waterdrop/utils/StringTemplate.java, src/main/scala/org/interestinglab/waterdrop/output/Elasticsearch.scala
1. 更新EsSparkSQL相关初始化配置[configure](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#cfg-mapping)
2. 应用StringTemplate模板
=> Rickyhuo.output.elasticsearch

src/main/scala/org/interestinglab/waterdrop/filter/Kv.scala, src/main/scala/org/interestinglab/waterdrop/filter/Remove.scala, src/main/scala/org/interestinglab/waterdrop/filter/Replace.scala, src/main/scala/org/interestinglab/waterdrop/input/Fake.scala, src/main/scala/org/interestinglab/waterdrop/output/FileOutputBase.scala
* Input插件增加 Fake, 这个插件的功能是能够自动生成假数据，不需要依赖外部其他服务。主要是用来对waterdrop做功能测试，性能测试时简化input插件配置对外部服务的依赖。
* Filter插件新增 Replace，功能是根据正则表达式的匹配，将指定字段内容替换为指定内容，仅替换匹配的部分。
=> Garyelephant.fea.plugins

src/main/scala/org/interestinglab/waterdrop/filter/Date.scala, src/main/scala/org/interestinglab/waterdrop/utils/DateParser.scala, src/main/scala/org/interestinglab/waterdrop/utils/FormatParser.scala, src/main/scala/org/interestinglab/waterdrop/utils/UnixMSParser.scala, src/main/scala/org/interestinglab/waterdrop/utils/UnixParser.scala
已完成
* 支持`simpleDateFormat`、`UNIX`、`UNIX_MS`
* 适配无`source_field`
* defalut_value
未完成
* locale
* time_zone
=> Rickyhuo.fea.date

build.sbt, src/main/scala/org/interestinglab/waterdrop/output/Mysql.scala
=> added Output MySQL

src/main/resources/META-INF/services/org.interestinglab.waterdrop.filter.BaseFilter, src/main/scala/org/interestinglab/waterdrop/filter/Convert.scala, src/main/scala/org/interestinglab/waterdrop/filter/Json.scala
1. 实现JSON，关于__ROOT__暂未解决
2. 实现Convert，支持String、Double、Long、Integer等类型转换
=> Rickyhuo.fea.json

docs/zh-cn/configuration/filter-plugins/Drop.docs, docs/zh-cn/configuration/filter-plugins/Drop.md, docs/zh-cn/configuration/filter-plugins/Split.docs, docs/zh-cn/configuration/filter-plugins/Split.md, docs/zh-cn/configuration/input-plugins/Kafka.docs, docs/zh-cn/configuration/input-plugins/Kafka.md, docs/zh-cn/configuration/input-plugins/Socket.docs, docs/zh-cn/configuration/input-plugins/Socket.md, docs/zh-cn/configuration/output-plugins/Elasticsearch.docs, docs/zh-cn/configuration/output-plugins/Elasticsearch.md, docs/zh-cn/configuration/output-plugins/Stdout.docs, docs/zh-cn/configuration/output-plugins/Stdout.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Split.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/Kafka.scala
* 新增3个文档：Input: Kafka, Filter: Split, Output: Elasticsearch
=> Garyelephant.docs.plugins

docs/zh-cn/_sidebar.md, docs/zh-cn/configuration/_sidebar.md, docs/zh-cn/deployment.md, docs/zh-cn/installation.md, docs/zh-cn/quick-start.md
* quick-start.md
* installation.md
=> Garyelephant.docs.quick start

bin/start-waterdrop.sh, docs/zh-cn/_sidebar.md, docs/zh-cn/configuration/_sidebar.md, docs/zh-cn/configuration/base.md, docs/zh-cn/deployment.md, docs/zh-cn/monitoring.md, docs/zh-cn/roadmap.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/CommandLineArgs.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/CommandLineUtils.scala
* 新增文档：roadmap
* 新增文档：部署与运行
* 新增文档：通用配置
* 修改start-waterdrop.sh，支持直接通过参数指定master, deploy-mode, 配置文件。
=> Garyelephant.docs.roadmap with deployment

docs/zh-cn/_sidebar.md, docs/zh-cn/configuration/_sidebar.md, docs/zh-cn/internal.md
=> added waterdrop internal docs

docs/zh-cn/configuration/filter-plugins/Table.docs, docs/zh-cn/configuration/filter-plugins/Table.md
=> added table filter docs

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/FileOutputBase.scala
=> Kid xiong.fixbug.#135

config/batch.conf.template, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/Hdfs.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/File.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/FileOutputBase.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/Hdfs.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/S3.scala
* fixed hdfs://, file://, s3:// URI schema://authority/path format
=> fixed hdfs://, file://, s3:// URI schema://authority/path format

config/batch.conf.template, config/streaming.conf.template, waterdrop-core/build.sbt, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ConfigCommand.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ConfigRuntimeException.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ConfigVisitorImpl.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/AsciiArt.java, waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseOutput, waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseStaticInput, waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseStreamingInput, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/ConfigBuilder.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/Fake2.scala
* fixed configbuilder plugin class not found
* removed reflections dependency
* added ascii art of waterdrop logo when started
* make config error infomation human-readable
=> Garyelephant.fix.configbuilder

docs/en/configuration/filter-plugins/Date.md, docs/zh-cn/configuration/filter-plugins/Date.md
=> Fix an error of date docs

docs/en/configuration/output-plugins/Clickhouse.md, docs/zh-cn/configuration/output-plugins/Clickhouse.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/Clickhouse.scala
为Output ClickHouse插件新增bulk_size参数，默认为无穷大，所有的数据会一次性发送至clickhouse http接口
=> Add bulk_size for clickhouse output

docs/en/configuration/input-plugins/Fake.md, docs/en/configuration/input-plugins/File.md, docs/en/configuration/input-plugins/Hdfs.md, docs/en/configuration/input-plugins/Jdbc.md, docs/en/configuration/input-plugins/KafkaStream.md, docs/en/configuration/input-plugins/MySQL.md, docs/en/configuration/input-plugins/S3.md, docs/en/configuration/input-plugins/Socket.md, docs/en/configuration/output-plugins/Clickhouse.md, docs/zh-cn/configuration/filter-plugins/Script.md, docs/zh-cn/configuration/input-plugins/File.md, docs/zh-cn/configuration/input-plugins/FileStream.md, docs/zh-cn/configuration/input-plugins/Hdfs.md, docs/zh-cn/configuration/input-plugins/HdfsStream.md, docs/zh-cn/configuration/input-plugins/Hive.md, docs/zh-cn/configuration/input-plugins/KafkaStream.md, docs/zh-cn/configuration/input-plugins/Kudu.md, docs/zh-cn/configuration/input-plugins/MongoDB.md, docs/zh-cn/configuration/input-plugins/S3Stream.md, docs/zh-cn/configuration/input-plugins/SocketStream.md, docs/zh-cn/configuration/output-plugins/Clickhouse.md, docs/zh-cn/configuration/output-plugins/Kudu.md, docs/zh-cn/configuration/output-plugins/MongoDB.md
更改插件文档中version版本号， 表示插件从哪个Waterdrop版本后才支持
=> Update plugin version

docs/en/configuration/filter-plugins/Lowercase.md, docs/en/configuration/filter-plugins/Uppercase.md, docs/zh-cn/configuration/filter-plugins/Lowercase.docs, docs/zh-cn/configuration/filter-plugins/Lowercase.md, docs/zh-cn/configuration/filter-plugins/Uppercase.docs, docs/zh-cn/configuration/filter-plugins/Uppercase.md
=> fixed typo of lowercase filter docs

.travis.yml
=> removed jdk7 in auto-build

build.sbt, docs/en/configuration/filter-plugins/Kv.md, docs/zh-cn/configuration/filter-plugins/Kv.md, waterdrop-core/build.sbt, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Kv.scala
* added `default_values` config in kv filter
=> added default_values config in kv filter

docs/en/configuration/output-plugins/Clickhouse.md, docs/zh-cn/configuration/output-plugins/Clickhouse.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/Clickhouse.scala
=> Rickyhuo.enhance.clickhouse

docs/zh-cn/configuration/input-plugins/FileStream.md, docs/zh-cn/configuration/input-plugins/HdfsStream.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/FileStream.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/HdfsStream.scala
* Support `XML` in fileStream and hdfsStream
=> Rickyhuo.fea.stream.xml

docs/zh-cn/configuration/input-plugins/File.md, docs/zh-cn/configuration/input-plugins/Hdfs.md, docs/zh-cn/configuration/output-plugins/File.md, docs/zh-cn/configuration/output-plugins/Hdfs.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/File.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/FileOutputBase.scala
=> Support format ORC

build.sbt, waterdrop-core/build.sbt
* Update elasticsearch-spark from 5.6.3 to 6.6.1
=> Update elasticsearch-spark version

docs/en/configuration/input-plugins/KafkaStream.md, docs/zh-cn/case_study/3.md, docs/zh-cn/case_study/base.md, docs/zh-cn/configuration/input-plugins/KafkaStream.md
* 更新`如何使用Spark快速将数据写入Elasticsearch` 一些配置详情
=> Update docs of 3.md

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Sql.scala
* added checkSQLSyntax in sql filter
=> added checkSQLSyntax in sql filter

docs/zh-cn/configuration/output-plugins/Opentsdb.md, waterdrop-core/build.sbt, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/entity/OpentsdbCallBack.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/HttpAsyncClient.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/HttpClientFactory.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/utils/HttpClientService.java, waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseStructuredStreamingOutput, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/structuredstreaming/Opentsdb.scala
1. 添加异步http包引用  2.新增Opentsdb输出插件
=> 1. 添加异步http包引用  2.新增Opentsdb输出插件

bin/start-waterdrop-structured-streaming.sh, bin/start-waterdrop.sh, build.sbt, waterdrop-core/build.sbt, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ExposeSparkConf.java
=> 修复了配置中spark部分无法使用变量替换的bug

build.sbt, config/batch.conf.template, config/complex.conf.template, config/structuredstreaming.conf.template, docs/zh-cn/configuration/base.md, docs/zh-cn/configuration/filter-plugin.md, docs/zh-cn/configuration/filter-plugins/Sql.md, docs/zh-cn/configuration/input-plugin.md, docs/zh-cn/configuration/output-plugin.md, waterdrop-apis/build.sbt, waterdrop-core/build.sbt, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/WaterdropStructuredStreaming.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Sql.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/structuredstreaming/KafkaStream.scala
* Add parameters of `source_table_name` AND `result_table_name` for Plugin
=> Rickyhuo.enhance.table view

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Clickhouse.scala
=> Update ClickHouse process to compatible with Null

config/structuredstreaming.conf.template, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/WaterdropStructuredStreaming.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Sql.scala
* 修复流式处理中，无法使用 `createOrReplaceTempView` 的问题
=> Fix a bug of streaming pipeline when register table view

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/ConfigBuilder.scala
=> Fix a bug of exception catch

docs/zh-cn/case_study/2.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Hive.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Kudu.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/MongoDB.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Tidb.scala
=> Rickyhuo.enhance.input

docs/zh-cn/configuration/input-plugins/Jdbc.md, docs/zh-cn/configuration/input-plugins/MySQL.md, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Jdbc.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Mysql.scala
=> Support jdbc optional option

config/spark.batch.conf.template, config/spark.streaming.conf.template, plugin-spark-source-kafka/src/main/scala/io/github/interestinglab/waterdrop/spark/source/KafkaStream.scala, waterdrop-apis/src/main/java/io/github/interestinglab/waterdrop/env/Execution.java, waterdrop-apis/src/main/java/io/github/interestinglab/waterdrop/plugin/Plugin.java, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ExposeSparkConf.java, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/Waterdrop.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/WaterdropFlink.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/config/ConfigBuilder.scala, waterdrop-spark-api/src/main/scala/io/github/interestinglab/waterdrop/spark/BaseSparkSource.scala, waterdrop-spark-api/src/main/scala/io/github/interestinglab/waterdrop/spark/batch/SparkBatchExecution.scala, waterdrop-spark-api/src/main/scala/io/github/interestinglab/waterdrop/spark/stream/SparkStreamingExecution.scala
Waterdrop v2 support `RESULT_TABLE_NAME` and `SOURCE_TABLE_NAME` of spark engine.
=> Rickyhuo.fea.wd2.view

README.md
* Update README.md Images urls
=> Update README.md Images urls

plugin-spark-phoenix-core/pom.xml, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/CsUtil.scala, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/DataFrameFunctions2.scala, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/PhoenixRDD2.scala, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/SparkSqlContextFunctions2.scala, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/ZkConnectUtil.scala, plugin-spark-phoenix-core/src/main/scala/org/apache/phoenix/spark/sparkExtend.scala, plugin-spark-sink-phoenix/pom.xml, plugin-spark-sink-phoenix/src/main/resources/services/io.github.interestinglab.waterdrop.spark.BaseSparkSink, plugin-spark-sink-phoenix/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Phoenix.scala, plugin-spark-source-phoenix/pom.xml, plugin-spark-source-phoenix/src/main/resources/services/io.github.interestinglab.waterdrop.spark.BaseSparkSource, plugin-spark-source-phoenix/src/main/scala/io/github/interestinglab/waterdrop/spark/source/Phoenix.scala, pom.xml, waterdrop-core/pom.xml
waterdrop phoenix source sink plugin 模块代码提交
=> Support phoenix source and sink for wd2

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Hive.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Kudu.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/FileOutputBase.scala
1. Fix bug of `table` in `kudu` and `hive`
2. Update output to support customize format
=> Fix bug of table_name and update file output

docs/en/configuration/output-plugins/Clickhouse.md, docs/zh-cn/v1/configuration/output-plugins/Clickhouse.md, waterdrop-core/build.sbt, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Clickhouse.scala
1.升级ClickHouse JDBC驱动到0.2.4
2.支持分布式表从system.clusters表读取配置，然后连接本地表写数据
=> new feature, support insert data to clickhouse distribute table

pom.xml, waterdrop-config/pom.xml
* Excluse pmd check for `waterdrop-config`
=> Using properties of skip.pmd.check

waterdrop-core/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.apis.BaseFilter, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/URLDecode.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/URLEncode.scala
* Plugin URLDecode
* Plugin URLEncode
=> Add filter plugins of urldecode and urlencode

bin/start-waterdrop.sh, waterdrop-core/src/main/java/io/github/interestinglab/waterdrop/config/ExposeSparkDriverConf.java
=> Rickyhuo.enhance.driverConf

waterdrop-flink-api/src/main/java/io/github/interestinglab/waterdrop/flink/util/SchemaUtil.java
=> fix bug #515

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Stdout.scala
=> Update output plugin of stdout to printSchema

build.md, plugin-flink-source-file/src/main/java/io/github/interestinglab/waterdrop/flink/source/FileSource.java, plugin-flink-source-kafka/src/main/java/io/github/interestinglab/waterdrop/flink/source/KafkaTableStream.java, waterdrop-dist/assembly.xml, waterdrop-flink-api/src/main/java/io/github/interestinglab/waterdrop/flink/util/SchemaUtil.java
=> Garyelephant.fix.package

waterdrop-core/build.sbt, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Redis.scala
通过模糊匹配keys获取对应的value，返回为 raw_key(key) --- raw_message(value) 的数据表
=> add redis batch source

plugin-spark-source-hive/pom.xml, plugin-spark-source-hive/src/main/resources/META-INF/services/io.github.interestinglab.waterdrop.spark.BaseSparkSource, plugin-spark-source-hive/src/main/scala/io/github/interestinglab/waterdrop/spark/source/Hive.scala, pom.xml, waterdrop-core/pom.xml
Add hive source code which is from waterdrop-1.x.
The doc is https://github.com/InterestingLab/waterdrop-docs/pull/25 . 
@garyelephant
=> Add hive source

plugin-spark-sink-email/pom.xml
Obvious pom.xml error  ,which cause compile fail
=> Obvious pom.xml error

plugin-spark-sink-console/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Console.scala
reference https://github.com/InterestingLab/waterdrop/pull/530
=> add printSchema to Console sink

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/output/batch/Hive.scala
=> 添加hive output

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/input/batch/Redis.scala
Usage:
host = "192.168.1.100"
key_pattern = "*key*"
partition = 3
db_num = 0
result_table_name = "table_name"
autho="xxx"
=> 修改redis读取，增加密码字段

README.md
Update the description about the seatunnel project
=> [Feature] Update Readme

README.md
=> [doc] Update seatunnel readme in branch v2

plugin-flink-sink-jdbc/pom.xml, plugin-flink-source-jdbc/pom.xml, plugin-spark-source-jdbc/pom.xml, pom.xml
Because the license is not in compliance, if you need to use MySQL, you can add it yourself
=> Modify MySQL dependency scope

.mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Add maven wrapper that can ease the development (they don't need to install maven as long as they have Java environment), and we can lock the maven version so that there is no version issues in the future.
FYI @CalvinKirs
=> Add maven wrapper to ease the development

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md
This PR add issue and pr template to repo
=> Add GitHub template for bug/feature issue and PR

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> Change issue template

README.md, README_zh_CN.md
=> [fix #696] need to update the picture

README.md
=> [fix #700] The link to the detailed documents on SeaTunnel is invalid

README.md
delete the invalid link of chat
add link to zh-CN readme doc
closes: #698
=> [fix-698] delete the invalid link of chat

.github/workflows/backend.yml
=> [CI]Run UT

.github/workflows/backend.yml, README.md
=> [CI] Switch CI branch to dev

.github/workflows/backend.yml, seatunnel-config/src/main/java/io/github/interestinglab/waterdrop/config/impl/AbstractConfigNode.java
=> [CI]code style check

plugin-flink-sink-elasticsearch/pom.xml, plugin-flink-sink-file/pom.xml, plugin-flink-sink-jdbc/pom.xml, plugin-flink-sink-kafka/pom.xml, plugin-flink-source-file/pom.xml, plugin-flink-source-jdbc/pom.xml, plugin-flink-source-kafka/pom.xml, plugin-spark-phoenix-core/pom.xml, plugin-spark-sink-clickhouse/pom.xml, plugin-spark-sink-elasticsearch/pom.xml, plugin-spark-sink-email/pom.xml, plugin-spark-sink-hbase/pom.xml, plugin-spark-source-elasticsearch/pom.xml, plugin-spark-source-kafka/pom.xml, pom.xml, seatunnel-common/pom.xml, seatunnel-core/pom.xml, seatunnel-dist/pom.xml, seatunnel-flink-api/pom.xml
---
This patch unify declare dependence in parent pom.xml
=> Declare dependence in parent pom

plugin-spark-sink-hbase/pom.xml
---
Fix https://github.com/InterestingLab/seatunnel/issues/717
```log
[dcadmin@dcadmin seatunnel-dist-2.0.4-2.11.8]$ bin/start-seatunnel-flink.sh 
Starting execution of program
[INFO] Loading config file: /work/projects/opensource/seatunnel/seatunnel-dist/seatunnel-dist-2.0.4-2.11.8/config/application.conf
[INFO] parsed config file: {
"env" : {
"execution.parallelism" : 1
},
"source" : [
{
"result_table_name" : "fake",
"plugin_name" : "FakeSourceStream",
"field_name" : "name,age"
}
],
"transform" : [
{
"plugin_name" : "sql",
"sql" : "select name,age from fake"
}
],
"sink" : [
{
"plugin_name" : "ConsoleSink"
}
]
}
*#*      *##*      *#*                                                           ##                                                      
*#*      *##*      *#* …
```
=> Fix throw ClassCastException when submit app to flink1.9.3

seatunnel-flink-api/pom.xml
---
Remove Chinese comment in flink-api pom.xml
=> Remove Chinese comment in flink-api pom.xml

plugin-spark-sink-email/pom.xml, plugin-spark-sink-mysql/pom.xml
closes: #735
---
add scala-maven-plugin to some plugin's pom.xml
=> [Issue-735] bugfix: add scala-maven-plugin to some plugin's pom.xml

pom.xml, seatunnel-dist/docker/README.md, seatunnel-dist/docker/quick-start/Dockerfile, seatunnel-dist/docker/quick-start/entrypoint.sh, seatunnel-dist/pom.xml
closes: #715 
---
add quick-start Dockerfile
=> [Feature#715] add quick-start Dockerfile

seatunnel-core/seatunnel-core-base/src/main/java/io/github/interestinglab/waterdrop/config/ConfigBuilder.java, seatunnel-flink-api/src/main/java/io/github/interestinglab/waterdrop/flink/batch/FlinkBatchExecution.java, seatunnel-flink-api/src/main/java/io/github/interestinglab/waterdrop/flink/stream/FlinkStreamExecution.java
=> [Implement] add flink Execution plan print

plugin-spark-sink-hbase/src/main/scala/io/github/interestinglab/waterdrop/spark/sink/Hbase.scala
=> [MINOR] Using camelCase style.

bin/start-seatunnel-sql.sh, seatunnel-core/pom.xml, seatunnel-core/seatunnel-core-sql/README.md, seatunnel-core/seatunnel-core-sql/pom.xml, seatunnel-core/seatunnel-core-sql/src/main/java/io/github/interestinglab/waterdrop/core/sql/WaterdropSql.java, seatunnel-core/seatunnel-core-sql/src/main/java/io/github/interestinglab/waterdrop/core/sql/job/Executor.java, seatunnel-core/seatunnel-core-sql/src/main/java/io/github/interestinglab/waterdrop/core/sql/job/JobInfo.java, seatunnel-core/seatunnel-core-sql/src/main/java/io/github/interestinglab/waterdrop/core/sql/splitter/SqlStatementSplitter.java, seatunnel-dist/assembly.xml
Currently, we just support basic transform framework. For more detail, please go to https://github.com/InterestingLab/seatunnel/issues/716
```sql
CREATE TABLE events (
f_type INT,
f_uid INT,
ts AS localtimestamp,
WATERMARK FOR ts AS ts
) WITH (
'connector' = 'datagen',
'rows-per-second'='5',
'fields.f_type.min'='1',
'fields.f_type.max'='5',
'fields.f_uid.min'='1',
'fields.f_uid.max'='1000'
);
CREATE TABLE print_table (
type INT,
uid INT,
lstmt TIMESTAMP
) WITH (
'connector' = 'print',
'sink.parallelism' = '1'
);
INSERT INTO print_table SELECT * FROM events where f_type = 1;
```
1. Please download flink1.13.3 https://repo.huaweicloud.com/apache/flink/flink-1.13.3/
2. Start flink 
```
bin/start-cluster.sh
```
3. Add sql to `application.conf`
```
CREATE TABLE events (
f_type INT,
f_uid INT, …
```
=> [SeaTunnel #757][Core] Add seatunnel-core-sql module

plugin-spark-sink-hudi/pom.xml, plugin-spark-source-kudu/pom.xml
We had changed the seatunnel-api structure, this patch fixed these wrong dependencies. 
For more, please go to https://github.com/InterestingLab/seatunnel/pull/796
=> [hotfix] fix wrong seatunnel-api dependency

.github/ISSUE_TEMPLATE/umbrella.yml
Fixed #780 
Add umbrella issue template.
=> [SeaTunnel #780][issue] Add umbrella issue template

.github/PULL_REQUEST_TEMPLATE.md, .idea/vcs.xml
We should have a unified pull request name form, like `SeaTunnel #xxx`, it will be useful for us when we want to read the issue.
Add `vcs.xml` will help us jump to issues directly id Intellij IDEA.
=> [SeaTunnel #804] [patch] Improve the pull_request template

deploy/docker/flink/config/application.conf, deploy/docker/spark/config/application.conf
=> Add license header

pom.xml, seatunnel-connectors/plugin-spark-sink-kafka/pom.xml
[Feature] Replace scala version 2.11 with ${scala.binary.version} in pom.xml #820
=> [Feature] Replace scala version 2.11 with ${scala.binary.version} in pom.xml

seatunnel-core/seatunnel-core-base/src/main/java/io/github/interestinglab/waterdrop/Waterdrop.java, seatunnel-core/seatunnel-core-base/src/main/java/io/github/interestinglab/waterdrop/utils/AsciiArtUtils.java, seatunnel-core/seatunnel-core-base/src/main/scala/io/github/interestinglab/waterdrop/config/CommandLineUtils.scala
[Bug] [seatunnel-core-base] Change AsciiLogo from Waterdrop to SeaTunnel #817
=> Change AsciiLogo from Waterdrop to SeaTunnel

.dlc.json
remove unused imports, this bug blocks #838 
https://github.com/InterestingLab/seatunnel/runs/4590145141?check_suite_focus=true
```
FILE: ./README.md
[✖] https://img.shields.io/badge/document-English-blue.svg
ERROR: 2 dead links found!
[✖] https://img.shields.io/badge/文档-中文版-blue.svg
16 links checked.
[✖] https://img.shields.io/badge/document-English-blue.svg → Status: 403
[✖] https://img.shields.io/badge/文档-中文版-blue.svg → Status: 403
Error: Process completed with exit code 1.
```
=> [hotfix] ignore unstable links

README.md, README_zh_CN.md
=> Add project logo

pom.xml
Remove useless maven properties
=> [MINOR] Remove useless version property

.asf.yaml
Set the merge method, review limit, label, website and GitBox
=> [Github]Configure Github

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/umbrella.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/publish-docker.yaml, .idea/vcs.xml, README.md, README_zh_CN.md, pom.xml
Congratulations! 
We need to replace the project github repository.
=> [repository] replace project github repository

.dlc.json
=> [Chore]Ignore some link check

README_zh_CN.md
=> [DOCS]Update README_zh_CN.md

README.md
=> [DOCS]Update README.md

seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/Seatunnel.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandLineArgs.java, seatunnel-core/seatunnel-core-base/src/test/java/org/apache/seatunnel/config/command/CommandLineUtilsTest.java, seatunnel-core/seatunnel-core-sql/src/main/java/org/apache/seatunnel/core/sql/SeatunnelSql.java
=> [MINOR] Fix misspelling

seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/Seatunnel.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/ConfigBuilder.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandFlinkArgs.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/config/command/CommandSparkArgs.java
closes #884
Need to create Spark/FlinkEnvironment according to Engine type，but the Engine is null.
=> [SeaTunnel #884] Fix NullPointerException caused by engine type

README.md, README_zh_CN.md
seatunnel-workflow picture in README the display effect is not good, the picture is not clear,  ".png" change to ".svg"
=> [SeaTunnel #908] [README] seatunnel-workflow image change.

seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/FlinkEnvironment.java, seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/util/EnvironmentUtil.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisOutputFormat.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisStreamLoad.java, seatunnel-connectors/seatunnel-connector-flink-file/src/main/java/org/apache/seatunnel/flink/sink/FileSink.java
Fixes class logger variable name, keep the same with other class file.
=> Fixes class logger variable name, keep the same with other class file.

seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/batch/FlinkBatchExecution.java, seatunnel-apis/seatunnel-api-spark/src/main/java/org/apache/seatunnel/spark/utils/SparkStructTypeUtil.java, seatunnel-connectors/seatunnel-connector-spark-mongodb/src/main/scala/org/apache/seatunnel/spark/source/MongoDB.scala
=> [style] Fix typo

docs/en/configuration/sink-plugins/Hive.md, seatunnel-connectors/seatunnel-connector-spark-hive/src/main/resources/META-INF/services/org.apache.seatunnel.spark.BaseSparkSink, seatunnel-connectors/seatunnel-connector-spark-hive/src/main/scala/org/apache/seatunnel/spark/sink/Hive.scala
=> [SeaTunnel #910] Support spark-hive sink

docs/en/configuration/source-plugins/Druid.md, pom.xml, seatunnel-connectors/pom.xml, seatunnel-connectors/seatunnel-connector-flink-druid/pom.xml, seatunnel-connectors/seatunnel-connector-flink-druid/src/main/java/org/apache/seatunnel/flink/source/DruidInputFormat.java, seatunnel-connectors/seatunnel-connector-flink-druid/src/main/java/org/apache/seatunnel/flink/source/DruidSource.java, seatunnel-connectors/seatunnel-connector-flink-druid/src/main/java/org/apache/seatunnel/flink/source/DruidSql.java, seatunnel-connectors/seatunnel-connector-flink-druid/src/main/resources/META-INF/services/org.apache.seatunnel.flink.BaseFlinkSource
=> Add Druid Flink Source plugin

README.md
1. add slack info
2. add twitter info
=> [Readme] update contact message

seatunnel-connectors/seatunnel-connector-spark-doris/src/main/scala/org/apache/seatunnel/spark/sink/Doris.scala, seatunnel-connectors/seatunnel-connector-spark-doris/src/main/scala/org/apache/seatunnel/spark/sink/DorisUtil.scala
I did it myself before but i found TypesafeConfigUtils could use
=> Optimize Use TypesafeConfigUtils

seatunnel-connectors/seatunnel-connector-flink-file/src/main/java/org/apache/seatunnel/flink/sink/JsonRowOutputFormat.java
This patch won't change the logic, just use `Collection`'s methods instead to simplify the code and improve the performance.
=> Use collection methods instead

.github/workflows/backend.yml, .github/workflows/publish-docker.yaml
This patch is trying to fix the pending problem of Github Action.
=> Fix Github Action pending problem

docs/en/configuration/source-plugins/Hudi.md, seatunnel-connectors/seatunnel-connector-spark-hudi/src/main/resources/META-INF/services/org.apache.seatunnel.spark.BaseSparkSource, seatunnel-connectors/seatunnel-connector-spark-hudi/src/main/scala/org/apache/seatunnel/spark/source/Hudi.scala
Spark-hudi source plugin 
closes #919
=> [SeaTunnel #919] Add spark-hudi source plugin 

README_zh_CN.md, config/spark.streaming.conf.template, plugins/json/files/schemas/seatunnel-demo.json, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/Seatunnel.java
=> [SeaTunnel #856][community] Migrate organization from interestinglab to apache

bin/start-seatunnel-sql.sh, seatunnel-core/seatunnel-core-flink/src/main/bin/start-seatunnel-flink.sh, seatunnel-core/seatunnel-core-spark/src/main/bin/start-seatunnel-spark.sh
Check required options in script instead of throw exception in program.
closes #953
=> [SeaTunnel #953] Check required options in script

docs/en/configuration/sink-plugins/Kudu.md, seatunnel-connectors/seatunnel-connector-spark-kudu/src/main/resources/META-INF/services/org.apache.seatunnel.spark.BaseSparkSink, seatunnel-connectors/seatunnel-connector-spark-kudu/src/main/scala/org/apache/seatunnel/spark/sink/Kudu.scala
=> [SeaTunnel #925] Add spark-kudu sink plugin

seatunnel-connectors/seatunnel-connector-spark-kudu/src/main/scala/org/apache/seatunnel/spark/sink/Kudu.scala
Fixes https://github.com/apache/incubator-seatunnel/issues/974
=> [SeaTunnel#974]Fix compile error caused by kudu plugin

pom.xml, seatunnel-apis/seatunnel-api-flink/pom.xml, seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/FlinkEnvironment.java, seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/util/ConfigKeyName.java
=> [Feature][API-FLINK] flink core add blink planner

waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/filter/Date.scala, waterdrop-core/src/main/scala/io/github/interestinglab/waterdrop/utils/TimestampParser.scala
=> [Feature][plugin-filter-date] Date filter supports Timestamp.

seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/FlinkEnvironment.java, seatunnel-apis/seatunnel-api-flink/src/main/java/org/apache/seatunnel/flink/util/SchemaUtil.java, seatunnel-config/src/main/java/com/typesafe/config/impl/ConfigNodePath.java, seatunnel-config/src/main/java/com/typesafe/config/impl/ConfigParser.java, seatunnel-config/src/main/java/com/typesafe/config/impl/PathParser.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisOutputFormat.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisStreamLoad.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/utils/CompressionUtils.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/utils/PluginType.java
Split the previous one https://github.com/apache/incubator-seatunnel/pull/982
=> [SeaTunnel#981] Split the Code Inspection PR

seatunnel-examples/pom.xml, seatunnel-examples/seatunnel-flink-examples/src/main/java/org/apache/seatunnel/example/flink/LocalFlinkExample.java, seatunnel-examples/seatunnel-spark-examples/pom.xml, seatunnel-examples/seatunnel-spark-examples/src/main/java/org/apache/seatunnel/example/spark/LocalSparkExample.java, seatunnel-examples/seatunnel-spark-examples/src/main/java/org/apache/seatunnel/test/spark/LocalTest.java, seatunnel-examples/seatunnel-spark-examples/src/main/resources/examples/spark.batch.conf.template
this closes https://github.com/apache/incubator-seatunnel/issues/961
spark local environment run quickly and debug locally developed code easily
=> [Feature][seatunnel-examples] spark local environment run quickly and debug locally developed code easily

seatunnel-examples/seatunnel-flink-examples/pom.xml
=> [Improvement][example]Use ${project.version} instead of deprecated ${parent.version}

README_zh_CN.md
=> [SeaTunnel#1006] Fix broken SeaTunnel logo in CN doc

pom.xml, seatunnel-examples/seatunnel-flink-examples/pom.xml
=> [SeaTunnel#989]Optimize maven config.

plugins/json/files/schemas/seatunnel-demo.json
We already have divided plugins into two categories: connectors and transforms, so we can remove the useless plugins folder.
=> [hotfix] remove plugins folder

README.md, README_zh_CN.md
=> [SeaTunnel#1016] All contributor avatars together

README.md
=> [SeaTunnel#1013] Remove useless NBSP from doc

README.md, README_zh_CN.md
Since https://github.com/apache/incubator-seatunnel/pull/923 and https://github.com/apache/incubator-seatunnel/pull/970 have been merged, we should add Druid into README docs
=> [SeaTunnel] [Doc] Add Druid into README docs

docs/en/configuration/sink-plugins/Doris-Flink.md, docs/en/configuration/sink-plugins/Doris.md
=> [SeaTunnel#1018] Fix the dead link of Doris

plugins/json/files/schemas/seatunnel-demo.json
Reverts apache/incubator-seatunnel#1009
this close #1023
=> [SeaTunnel#1023]Revert "[hotfix] remove plugins folder"

seatunnel-core/seatunnel-core-sql/pom.xml, seatunnel-core/seatunnel-core-sql/src/main/java/org/apache/seatunnel/core/sql/splitter/SqlStatementSplitter.java, seatunnel-core/seatunnel-core-sql/src/test/java/org/apache/seatunnel/core/sql/splitter/SqlStatementSplitterTest.java
Add SqlStatementSplitter test case 
Fix sql spliter single line bug
=> [SeaTunnel #783][UT] Add SqlStatementSplitter test case 

.github/workflows/codeql.yaml
=> [SeaTunnel][CI]Add codeQL action

seatunnel-core/seatunnel-core-flink/src/main/bin/start-seatunnel-flink.sh, seatunnel-core/seatunnel-core-spark/src/main/bin/start-seatunnel-spark.sh
=> [SeaTunnel#999] startup scripts need source seatunnel-env.sh

config/seatunnel-env.sh, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/Seatunnel.java
=> [SeaTunnel #998] add an environment variable to control print AsciiLogo

docs/en/flink/configuration/sink-plugins/InfluxDb.md, pom.xml, seatunnel-connectors/pom.xml, seatunnel-connectors/seatunnel-connector-flink-influxdb/pom.xml, seatunnel-connectors/seatunnel-connector-flink-influxdb/src/main/java/org/apache/seatunnel/flink/sink/InfluxDbOutputFormat.java, seatunnel-connectors/seatunnel-connector-flink-influxdb/src/main/java/org/apache/seatunnel/flink/sink/InfluxDbSink.java, seatunnel-connectors/seatunnel-connector-flink-influxdb/src/main/resources/META-INF/services/org.apache.seatunnel.flink.BaseFlinkSink
=> [SeaTunnel #1037] Add InfluxDB Flink Sink

deploy/docker/flink/README.md
=> [SEATUNNEL#1056] fix document error in docker deploy

seatunnel-config/src/main/java/com/typesafe/config/impl/PathParser.java, tools/checkstyle/checkStyle.xml
=> [SeaTunnel#1071] Enable the InnerTypeLast rule in checkstyle and fix it

config/flink.sql.conf.template
=> [SeaTunnel #949] [sql] Add sql conf template

seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisOutputFormat.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisSink.java, seatunnel-connectors/seatunnel-connector-flink-doris/src/main/java/org/apache/seatunnel/flink/sink/DorisStreamLoad.java, seatunnel-connectors/seatunnel-connector-flink-elasticsearch/src/main/java/org/apache/seatunnel/flink/sink/Elasticsearch.java, seatunnel-connectors/seatunnel-connector-flink-fake/src/main/java/org/apache/seatunnel/flink/source/FakeSourceStream.java, seatunnel-connectors/seatunnel-connector-flink-file/src/main/java/org/apache/seatunnel/flink/sink/CsvRowOutputFormat.java, seatunnel-connectors/seatunnel-connector-flink-file/src/main/java/org/apache/seatunnel/flink/source/FileSource.java, seatunnel-connectors/seatunnel-connector-flink-jdbc/src/main/java/org/apache/seatunnel/flink/sink/JdbcSink.java, seatunnel-connectors/seatunnel-connector-flink-kafka/src/main/java/org/apache/seatunnel/flink/source/KafkaTableStream.java, seatunnel-connectors/seatunnel-connector-flink-socket/src/main/java/org/apache/seatunnel/flink/source/SocketStream.java, seatunnel-core/seatunnel-core-base/src/main/java/org/apache/seatunnel/utils/AsciiArtUtils.java, tools/checkstyle/checkStyle.xml
=> [SEATUNNEL#1060] Enable the MagicNumber rule in checkstyle and fix them

pom.xml, seatunnel-core/seatunnel-core-flink/pom.xml, seatunnel-core/seatunnel-core-spark/pom.xml, seatunnel-core/seatunnel-core-sql/pom.xml
=> [SeaTunnel#1021] make maven-shade-plugin only applied to core modules

bin/start-seatunnel-sql.sh, seatunnel-core/seatunnel-core-flink/src/main/bin/start-seatunnel-flink.sh, seatunnel-core/seatunnel-core-spark/src/main/bin/start-seatunnel-spark.sh
fixed #1052 
Infinite loop in script
=> [SeaTunnel #1052][Bug] Fix infinite loop in script

docs/en/connector-v2/sink/DB2.md, docs/en/connector-v2/sink/HdfsFile.md, docs/en/connector-v2/sink/Kingbase.md, docs/en/connector-v2/sink/Mysql.md, docs/en/connector-v2/sink/OceanBase.md, docs/en/connector-v2/sink/Oracle.md, docs/en/connector-v2/sink/PostgreSql.md, docs/en/connector-v2/sink/S3File.md, docs/en/connector-v2/sink/Snowflake.md, docs/en/connector-v2/sink/Vertica.md, docs/en/connector-v2/source/HdfsFile.md
[New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
=> [Improve][Doc] Update old links in doc
